name: compound
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # http request
  http: ^0.13.0

  # async package to add additional Cancellable operations
  async: ^2.0.8

  # get it
  get_it: ^7.2.0

  # provider
  provider: ^6.0.1

  # MVVM
  stacked: ^2.2.7+1

  # firebase-related
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0

  # others
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/title.png
    - assets/images/icon_large.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
