name: analog_clock
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # manually added
  google_fonts: ^2.1.0
  # flutter_svg: ^0.18.0 # it helps us to use SVG in our app
  flutter_svg: ^0.20.0-nullsafety.3
  provider: ^4.3.2+1 # Our state management package
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - assets/icons/
